package utils

const UNEXPECTED_CHARACTER_MESSAGE = "Unexpected character"
const UNTERMINATED_STRING = "Unterminated string"
const INVALID_NUMBER = "Invalid number"
const UNMATCHED_PAREN = "Unmatched paren"
const INVALID_OPERAND_NUMBER = "Operand must be a number"
const INVALID_OPERAND_NUMBERS = "Operands must be numbers"
const EXPECT_SEMICOLON_AFTER_VALUE = "Expect ';' after value"
const EXPECT_VARIABLE_NAME = "Expect variable name"
const EXPECT_SEMICOLON_AFTER_VARIABLE_DECLARATION = "Expect ';' after variable declaration"
const INVALID_ASSIGNMENT_TARGET = "Invalid assignment target"
const EXPECT_RIGHT_BRACE_AFTER_BLOCK = "Expect '}' after block"
const EXPECT_LEFT_PAREN_AFTER_IF = "Expect '(' after 'if'"
const EXPECT_RIGHT_PAREN_AFTER_IF_CONDITION = "Expect ')' after if condition"
const EXPECT_LEFT_PAREN_AFTER_WHILE = "Expect '(' after while"
const EXPECT_RIGHT_PAREN_AFTER_CONDITION = "Expect ')' after condition"
const EXPECT_LEFT_PAREN_AFTER_FOR = "Expect '(' after for"
const EXPECT_SEMICOLON_AFTER_LOOP_CONDITION = "Expect ';' after loop condition"
const EXPECT_RIGHT_PAREN_AFTER_CLAUSES = "Expect ')' after clauses"

const UNDEFINED_VARIABLE = "Undefined variable %s\n"
